package com.github.tiagopalhota.kafka.tutorial3;

import com.google.gson.JsonParser;
import org.apache.http.HttpHost;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.nio.client.HttpAsyncClientBuilder;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.elasticsearch.action.bulk.BulkRequest;
import org.elasticsearch.action.bulk.BulkResponse;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.action.index.IndexResponse;
import org.elasticsearch.client.RequestOptions;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestClientBuilder;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.common.xcontent.XContentType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.time.Duration;
import java.util.Arrays;
import java.util.Properties;

public class ElasticSearchConsumer {

    public static RestHighLevelClient createClient() {

        String hostname = "bonsai.io hostname here";
        String username = "username";
        String password = "password";

       /*
        String connString = System.getenv("BONSAI_URL");
        URI connUri = URI.create(connString);
        String[] auth = connUri.getUserInfo().split(":");
        */

        final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();

        credentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(username, password));

        RestClientBuilder builder = RestClient.builder(new HttpHost(hostname, 443, "https")).setHttpClientConfigCallback(new RestClientBuilder.HttpClientConfigCallback() {
            @Override
            public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpAsyncClientBuilder) {
                return httpAsyncClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
            }
        });

        RestHighLevelClient client = new RestHighLevelClient(builder);

        return client;
    }


    public static void main(String[] args) throws IOException {


        Logger logger = LoggerFactory.getLogger(ElasticSearchConsumer.class.getName());
        RestHighLevelClient client = createClient();

        //  IndexRequest indexRequest = new IndexRequest("twitter", "tweets").source(jsonString, XContentType.JSON);



        // create the consumer
        KafkaConsumer<String, String> consumer = createConsumer("twitter_demo");

        while(true){
            ConsumerRecords<String, String> records = consumer.poll(Duration.ofMillis(100));

            logger.info("Received : " + records.count() + " records");

            BulkRequest bulkRequest = new BulkRequest();


            for(ConsumerRecord<String,String> record : records){
                /*
                    2 strategies to make generic IDs
                    so that we make the insertion idempotent and avoid duplicates
                 */
                // GENERIC ID that we can always use if we cant find a better id
                // as each message is always identifiable by topic,partition and offset
                // String id = record.topic()  + "_" + record.partition() + "_" + record.offset();


                try{
                    //let's use the Twitter id ( generated by Twitter)
                    String id = extractIDFromTweet(record.value());

                    // where we insert data into elastic search
                    String jsonValue = record.value();

                    IndexRequest indexRequest = new IndexRequest("twitter", "tweets", id)
                            .source(jsonValue, XContentType.JSON);

                    bulkRequest.add(indexRequest);


                }catch(NullPointerException e){
                    logger.warn("skipping bad data:  " + record.value());

                }



                /*
                IndexResponse indexResponse = client.index(indexRequest, RequestOptions.DEFAULT);

                We were doing this before but this is doing one request per record, making it
                very slow. Now we use a bulkRequest
                 */

            }


            if(records.count() > 0){
                // now time to make the bulk batched request
                BulkResponse bulkResponse = client.bulk(bulkRequest, RequestOptions.DEFAULT);
                logger.info("Commiting offsets...");
                consumer.commitSync();
                logger.info("Offsets have been committed");

            }

            try{
                Thread.sleep(2000);

            }catch(InterruptedException e){
                e.printStackTrace();
            }

        }


        // close the client gracefully
        //client.close();


    }

    public static KafkaConsumer<String, String > createConsumer(String topic){
        String bootstrapServers = "localhost:9092";
        String groupID = "kafka-demo-elasticsearch";

        Properties properties = new Properties();
        properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        properties.setProperty(ConsumerConfig.GROUP_ID_CONFIG, groupID);
        properties.setProperty(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, "3");

        // manage record offsets manually to only record offsets after processing it.
        properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false");
        // earliest -> read from the beginning of the topic
        // latest -> only new messages
        // none -> throws an error
        properties.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");

        // Create a consumer
        KafkaConsumer<String, String> consumer = new KafkaConsumer<String, String>(properties);


        //subscribe the consumer
        consumer.subscribe(Arrays.asList(topic));


        return consumer;
    }

    private static JsonParser jsonParser = new JsonParser();

    private static String extractIDFromTweet(String tweetJSON){
        //gson library
        return jsonParser.parse(tweetJSON).getAsJsonObject().get("id_str").getAsString();


    }
}
